### ISSUE TITLE
Similar script in the reHackable scripts repo

### ISSUE THREAD

**Issue by Ameb** [adaerr/reMarkableScripts#1]
Hello!
First i want to thank you for the script. There are other developers developing scripts for the rM tablet in the [reHackable github org](https://github.com/reHackable):  [reHackable/scripts](https://github.com/reHackable/scripts).

And there is another script wich does the same thing than [`pdf2remarkable.sh`](https://github.com/adaerr/reMarkableScripts/blob/master/pdf2remarkable.sh) (uploading files to the reMarkable), [`repush.sh`](https://github.com/reHackable/scripts/blob/master/host/repush.sh).  

Your aproach is kinda manual while repush uses the USB interface.  It might be possible to add your script to the reHackable repo, or merge both scripts into one with more funcionalities?

**Comment by homotopycolimit** [comment]
I should add that I cannot use the USB interface and always have to push via the wifi IP address. 
This script is the only one that works for me. (using QubesOS 4.0)

**Comment by edsu** [comment]
I must admit I like that this uses the IP address and does not require USB to be connected for the web server. I also like that it is fairly short and easy to read and understand exactly what it is doing, which is a bit harder with an 800 line program.

**Comment by adaerr** [comment]
Hi all,

Thanks for your comments. The reHackable repush script looks interesting indeed. Using the public upload API of the web interface makes it somewhat safer/futureproof, whereas this script will break if one day the file structure on the remarkable changes.

As pointed out, using ssh has its advantages though. With recent remarkable os versions requiring explicit enabling of the web interface after every restart, ssh is quicker too.

So as usual in the FOSS universe, there are several tools doing the job in a slightly different way, and I think that's good for the ecosystem and its users ;-)
