### ISSUE TITLE
epub2remarkable?

### ISSUE THREAD

**Issue by Jab2870** [adaerr/reMarkableScripts#10]
Do you have any plans to create an epub2remarkable.sh?

I have tried creating a $uuid.metadata and $uuid.epub file and copying them to
my remarkable but it only shows 1 empty page and it is considered a notebook.

**Comment by Jab2870** [comment]
So, it turns out the $uuid.content file needs to contain 

```
{ "fileType": "epub" }
```

I would be very happy to create a PR if you like? Before I do though, would you
prefer a seperate epub2remarkable.sh script, or would you like to adapt the
existing script so it can determine what to do based on the file type or a
command line flag?

**Comment by adaerr** [comment]
Hi Jonathan,
Thanks for your observations. I don't use epub very much currently, so I'm glad you resolved the issue yourself as I wouldn't have been of much help. PR on this welcome! If the only difference is this single line of metadata, I'd favor keeping a single script to factor the common code. Then maybe create a symbolic link epub2remarkable pointing to pdf2remarkable. Or are there many users allergic to name-space pollution ;-) ?
