### ISSUE TITLE
`uuidgen` on macOS produces uppercased output

### ISSUE THREAD

**Issue by Mausy5043** [adaerr/reMarkableScripts#12]
Hi,
On macOS `uuidgen` produces output using uppercase characters, while the reMarkable native form is in lowercase.

Please consider changing:    
https://github.com/adaerr/reMarkableScripts/blob/24c8585bcaff1bec7d178a77229c9973bafa175d/pdf2remarkable.sh#L94

to:    
`uuid=$(uuidgen | tr '[:upper:]' '[:lower:]')`

This will produce more consistent uuid's regardless of the OS or shell used.

**Comment by adaerr** [comment]
I figure this is more about esthetics in the sense that uppercase UUIDs will still work on the remarkable ? Anyway as `tr' is a coreutil your suggestion should not break anyone's configuration, so I added it in commit dee636f. Thanks for providing the patch.
